### ISSUE TITLE
Nodes looping back on each other

### ISSUE THREAD

**Issue by jfinge** [jinfang134/vue-pipeline#12]
With data like this: 

`[{name:'0',next:[{index:1},{index:3}]},{name:'1',next:[{index:2},{index:3}]},{name:'2',next:[]},{name:'3',next:[]}]`

the arrow between node 1 and 3 is coming around backwards: 

![example](https://user-images.githubusercontent.com/68400862/87720583-c566af00-c77a-11ea-8923-1d4f6dc14c4b.PNG)

**Comment by jinfang134** [comment]
ehhh, it is interesting. I will check and fix it.

**Comment by jinfang134** [comment]
fixed
