### ISSUE TITLE
建议给节点增加一个状态 running 运行状态

### ISSUE THREAD

**Issue by weiweidong1993** [jinfang134/vue-pipeline#7]
或者可以自定义状态

一点小意见  作者大大还在更新吗

**Comment by weiweidong1993** [comment]
尚未运行状态  unrunningStatus

运行状态 runningStatus

**Comment by jinfang134** [comment]
好的，我添加一下

**Comment by weiweidong1993** [comment]
> 好的，我添加一下

党中央高度关注此项目,请务必持续更新下去^_^

**Comment by jinfang134** [comment]
加好了，请看demo, https://jinfang134.github.io/vue-pipeline/

**Comment by jinfang134** [comment]
自定义状态有点难吧，因为节点的svg组件不方便传进去

**Comment by weiweidong1993** [comment]
> 加好了，请看demo, https://jinfang134.github.io/vue-pipeline/

好的 ok

**Comment by legenself** [comment]
建议running动画 不用elementui中的 动画吧，这样可以独立一些
